### ISSUE TITLE
Missing variables from EDGE-T and redundancy to REMIND

### ISSUE THREAD

**Issue by orichters** [pik-piam/edgeTransport#244]
These variables are currently redundant between EDGE-T and REMIND:
- Emi|CO2|Energy|Demand|Transport (Mt CO2/yr)
- Emi|CO2|Energy|Demand|Transport|Gases (Mt CO2/yr)
- Emi|CO2|Energy|Demand|Transport|Liquids (Mt CO2/yr)

Maybe you can check which of the variables do not exist anymore in EDGE-T and replace them in piamInterfaces by something appropriate:

The following 9 variables are expected in the piamInterfaces package for template AR6, but cannot be found in the reporting:
- [x] Emi|CO2|Transport|Freight|Short-Medium Distance|Demand (Mt CO2/yr), see [PR](https://github.com/pik-piam/piamInterfaces/pull/331)
- [x] Emi|CO2|Transport|Pass|Short-Medium Distance|Demand (Mt CO2/yr), see [PR](https://github.com/pik-piam/piamInterfaces/pull/331)
- [x] ES|Transport|VKM|Road (bn vkm/yr), -> https://github.com/pik-piam/edgeTransport/pull/245
- [ ] FE|Transport|Freight|Liquids|Biomass (EJ/yr),
- [ ] FE|Transport|Freight|Liquids|Hydrogen (EJ/yr),
- [ ] FE|Transport|Freight|Liquids|Oil (EJ/yr),
- [ ] FE|Transport|Pass|Liquids|Hydrogen (EJ/yr),
- [x] FE|Transport|Pass|Road|LDV|Two-Wheelers (EJ/yr), -> https://github.com/pik-piam/piamInterfaces/pull/282
- [x] UE|per capita|Transport|Pass (GJ/cap/yr) see [PR](https://github.com/pik-piam/piamInterfaces/pull/331)

The following 3 variables are expected in the piamInterfaces package for template NAVIGATE, but cannot be found in the reporting:
- [x] ES|Transport|Pass|Road|LDV|Two-Wheelers (bn pkm/yr), -> https://github.com/pik-piam/piamInterfaces/pull/282
- [x] FE|Transport edge (EJ/yr), -> https://github.com/pik-piam/piamInterfaces/pull/329
- [x] FE|Transport|Pass|Pass|w/o Bunkers (EJ/yr) -> https://github.com/pik-piam/piamInterfaces/pull/329

**Comment by jmuessel** [comment]
I did not check the following variables in the last. They are not there, yet, but might be in the medium-term future. We will continue with deleting the variables of introducing those into edgeT after the refactoring. If we introduce new ones, Liquids|Oil would be named Liquids|Fossil

FE|Transport|Freight|Liquids|Biomass (EJ/yr),
FE|Transport|Freight|Liquids|Hydrogen (EJ/yr),
FE|Transport|Freight|Liquids|Oil (EJ/yr),
FE|Transport|Pass|Liquids|Hydrogen (EJ/yr),

**Comment by orichters** [comment]
After refactoring, see `/p/tmp/oliverr/remind-smallfix/output/SSP2-NDC_2024-08-06_13.35.26/log.txt`

The following 16 variables are expected in the piamInterfaces package for mapping AR6, but cannot be found in the reporting:
- ES|Transport|Bunkers|Freight|International Shipping (bn tkm/yr),
- ES|Transport|Bunkers|Pass|International Aviation (bn pkm/yr),
- ES|Transport|Freight|Domestic Shipping (bn tkm/yr),
- ES|Transport|Freight|Rail (bn tkm/yr),
- ES|Transport|Freight|Road (bn tkm/yr),
- ES|Transport|Pass|Domestic Aviation (bn pkm/yr),
- ES|Transport|Pass|Non-motorized (bn pkm/yr),
- ES|Transport|Pass|Rail (bn pkm/yr),
- ES|Transport|Pass|Road (bn pkm/yr),
- ES|Transport|Pass|Road|Bus (bn pkm/yr),
- ES|Transport|Pass|Road|LDV (bn pkm/yr),
- ES|Transport|VKM|Road (bn vkm/yr),
- FE|Transport|Freight|Liquids|Oil (EJ/yr),
- FE|Transport|Pass|Road|LDV|Two-Wheelers (EJ/yr),
- Stock|Transport|Pass|Road|Bus (Million vehicles),
- Stock|Transport|Pass|Road|LDV (Million vehicles)

The latter two are probably just a [unit mismatch](https://github.com/pik-piam/edgeTransport/issues/268)

The following 15 variables are expected in the piamInterfaces package for mapping NAVIGATE, but cannot be found in the reporting:
- ES|Transport|Bunkers|Pass|International Aviation (bn pkm/yr),
- ES|Transport|Freight|Domestic Shipping (bn tkm/yr),
- ES|Transport|Freight|Rail (bn tkm/yr),
- ES|Transport|Freight|Road (bn tkm/yr),
- ES|Transport|Pass|Domestic Aviation (bn pkm/yr),
- ES|Transport|Pass|Non-motorized|Cycle (bn pkm/yr),
- ES|Transport|Pass|Non-motorized|Walk (bn pkm/yr),
- ES|Transport|Pass|Rail (bn pkm/yr),
- ES|Transport|Pass|Road (bn pkm/yr),
- ES|Transport|Pass|Road|Bus (bn pkm/yr),
- ES|Transport|Pass|Road|LDV (bn pkm/yr),
- ES|Transport|Pass|Road|LDV|Two Wheelers (bn pkm/yr),
- FE|Transport|LDV|Electricity (EJ/yr),
- FE|Transport|LDV|Gases (EJ/yr),
- FE|Transport|LDV|Hydrogen (EJ/yr)

**Comment by orichters** [comment]
I fixed the last missing variables from EDGE-T in https://github.com/pik-piam/piamInterfaces/pull/384

**Comment by jmuessel** [comment]
Thank you @orichters!
