### ISSUE TITLE
Duplicated Variable from toolReportEDGET()

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/edgeTransport#249]
Passenger and freight transportation are reported both with the same variable name `ES|Transport edge|Road`.

**Comment by orichters** [comment]
Just noted the difference in units between the two. So I think summing them is just a bit pointless anyway.

You might need to convert persons to tons using average passenger mass :duck:

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
tpe – tonne of person equivalent.  But that is a highly regionalised unit, with heavy variations from say USA to Somalia …

**Comment by orichters** [comment]
With EDGE-T 2.0, the fact that the variable is duplicated is now solved, but I do not understand the meaning of the unit `billion (p|t)km/yr` for `ES|Transport` and subvariables. Is it just the sum of pkm + tkm, so basically assuming a "tonne of person equivalent", as @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q called it, set to 1?

**Comment by LaviniaBaumstark** [comment]
can this issue be closed?
